version: '3'

services:
  web:
    build: .
    container_name: flask_app
    command: gunicorn -b 0.0.0.0:8000 --workers=4 app:app
    volumes:
      - .:/app
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
